### ISSUE TITLE
"Congestion situation" is displayed incorrectly on the Chinese page

### ISSUE THREAD

**Issue by li-qi-cool** [open-v2x/centerview#10]
## Describe the bug

When "congestion situation" is displayed as "free flow", after switching to Chinese, "自由流" is displayed, and the information is incomplete

## To Reproduce

Reference description

## Expected behavior

Reference description

## Screenshots

![截屏2022-07-30 上午9 38 24](https://user-images.githubusercontent.com/100892547/181865746-18d756da-14ef-43d2-88a2-62c41dbbcbad.png)
![截屏2022-07-30 上午9 39 08](https://user-images.githubusercontent.com/100892547/181865751-78c99623-7231-400a-8b11-8e6ff7ed13dd.png)

## Log Information

N/A

## Desktop (please complete the following information)

- OS: MACOS
- Browser: chrome
- Version/branch: master/albany

## Additional context

N/A

**Comment by moweiwei** [comment]
https://zh.wikipedia.org/zh-tw/%E4%B8%89%E7%9B%B8%E4%BA%A4%E9%80%9A%E7%90%86%E8%AE%BA  
![image](https://user-images.githubusercontent.com/40727882/181872167-f22b4abc-0e7f-4409-8a46-45f3ed6da38e.png)

’free flow‘ translate to '自由流' is ok
